---
kind: pipeline
type: aws
name: default

pool:
  use: windows

steps:
- name: check install
  commands:
  - 'type C:\ProgramData\Amazon\EC2-Windows\Launch\Log\UserdataExecution.log'

- name: install chocolatey
  commands:
  - 'Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString("https://community.chocolatey.org/install.ps1"))'