---
kind: pipeline
type: aws
name: default

pool:
  use: windows

steps:
- name: check install
  commands:
  - 'type C:\ProgramData\Amazon\EC2-Windows\Launch\Log\UserdataExecution.log'

- name: install choco
  commands:
  - 'powershell choco-install.ps1'