---
kind: pipeline
type: aws
name: default

pool:
  use: windows

steps:
- name: check install
  commands:
  - 'type C:\ProgramData\Amazon\EC2-Windows\Launch\Log\UserdataExecution.log'

- name: install choco
  commands:
  - '@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"'

- name: install dependencies
  commands:
  - choco install python --version 3.7.9 -y -ForceX86
  - python -v