---
kind: pipeline
type: aws
name: default

pool:
  use: windows

steps:
- name: check install
  commands:
  - 'type C:\ProgramData\Amazon\EC2-Windows\Launch\Log\UserdataExecution.log'

- name: Upgrade chocolatey
  commands:
  - 'choco upgrade chocolatey -y'

- name: Install Python
  environment:
    PYTHON3_32: C:\python37\python.exe
  commands:
  - 'choco install python --version 3.7.9 -y -ForceX86'
  - '&$env:PYTHON3_32 -V'