production:
  type: deploy
  script:
    - pip install --upgrade pip
    - pip install --upgrade -r requirements.txt
    - cd src
    - python setup.py py2exe
    - cd ..
    - cd scripts
    - python prepare_zipversion.py
    - cd ..
    - move src\socializer.zip socializer.zip
  only:
    - master
  artifacts:
    paths:
    - socializer.zip
    name: socializer
    expire_in: 1 week