variables:
  PYTHON3_32: "C:\\python39\\python.exe"
  #PYTHON3_64: "C:\\python37-64\\python.exe"
  #NSIS: "C:\\nsis\\makensis.exe"

.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

stages:
  - build
  - test

before_script:
 - Set-Variable -Name "time" -Value (date -Format "%H:%m")
 - echo ${time}
 - echo "started by ${GITLAB_USER_NAME}"
 - choco install python3 -y
 - refreshenv
 - '&$env:PYTHON3_32 -V'
 - '&$env:PYTHON3_32 -m pip install --upgrade pip'
 - '&$env:PYTHON3_32 -m pip install --upgrade -r requirements.txt'
 - '&$env:PYTHON3_32 -m pip uninstall enum34 -y'
 - python -V

test:
  extends:
  - .shared_windows_runners
  stage: test
  script:
  - echo "running scripts in the test job"
  - python -V