production:
  type: deploy
  script:
    - pip install --upgrade -r requirements.txt
    - cd src
    - python setup.py py2exe
    - cd ..
    - move src\dist socializer
  only:
    - tags
  artifacts:
    paths:
    - socializer\*
    name: socializer
    expire_in: 1 week