# Jobs to build the two channels in Socializer.
variables:
  PYTHON3: "C:\\python37\\python.exe"
  PYINSTALLER: "C:\\python37\\scripts\\pyinstaller.exe"
  PYTHON2: "C:\\python27\\python.exe"
  NSIS: "C:\\nsis\\makensis.exe"

test_py3:
  stage: test
  tags:
    - windows10
  before_script:
    - '%PYTHON3% -V'
    - '%PYTHON3% -m pip install --upgrade pip'
    - '%PYTHON3% -m pip install --upgrade -r requirements.txt'
  only:
    - schedules
  script:
    - cd src
    - '%PYTHON3% -m coverage run run_tests.py'
    - '%PYTHON3% -m coverage report --omit="test*"'
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

.alpha:
  type: deploy
  tags:
    - windows
  script:
    - pip install --upgrade pip
    - pip install --upgrade -r requirements.txt
    - copy changelog.md doc\changelog.md
    - cd doc
    - python documentation_importer.py
    - cd ..\src
    - python ..\doc\generator.py
    - python write_version_data.py
    - python setup.py py2exe
    - cd ..
    - cd scripts
    - python prepare_zipversion.py
    - cd ..
    - move src\socializer.zip socializer.zip
  only:
    - schedules
  artifacts:
    paths:
    - socializer.zip
    name: socializer
    expire_in: 1 day

alpha_python3:
  type: deploy
  tags:
    - windows10
  before_script:
    - '%PYTHON3% -v'
    - '%PYTHON3% -m pip install --upgrade pip'
    - '%PYTHON3% -m pip install --upgrade -r requirements.txt'
    - '%PYTHON3% -m pip uninstall enum34 -y'
  script:
    - copy changelog.md doc\changelog.md
    - cd doc
    - '%PYTHON2% documentation_importer.py'
    - cd ..\src
    - '%PYTHON2% ..\doc\generator.py'
    - '%PYTHON3% write_version_data.py'
    - '%PYINSTALLER% main.spec'
    - cd ..
    - cd scripts
    - '%PYTHON3% prepare_zipversion.py'
    - call genpot_interface.bat
    - call genpot_doc.bat
    - cd ..
    - move src\socializer.zip socializer.zip
    - move scripts\socializer.pot socializer.pot
    - move scripts\socializer-documentation.pot socializer-documentation.pot
  only:
    - schedules
  artifacts:
    paths:
    - socializer.zip
    - socializer.pot
    - socializer-documentation.pot
    name: socializer_py3
    expire_in: 1 day

stable:
  type: deploy
  tags:
    - windows
  before_script:
    - '%PYTHON3% -v'
    - '%PYTHON3% -m pip install --upgrade pip'
    - '%PYTHON3% -m pip install --upgrade -r requirements.txt'
    - '%PYTHON3% -m pip uninstall enum34 -y'
  script:
    - copy changelog.md doc\changelog.md
    - cd doc
    - '%PYTHON2% documentation_importer.py'
    - cd ..\src
    - '%PYTHON2% ..\doc\generator.py'
    - '%PYTHON3% write_version_data.py'
    - '%PYINSTALLER% main.spec'
    - '%NSIS% installer.nsi'
    - cd ..
    - move src\socializer* .
    - cd scripts
    - '%PYTHON3% prepare_zipversion.py'
    - cd ..
    - move src\socializer.zip socializer.zip
  only:
    - tags
  artifacts:
    paths:
    - socializer.zip
    - "socializer_*"
    name: socializer