# Jobs to build the two channels in Socializer.
# Currently using python 3.7.5
variables:
  PYTHON3_32: "C:\\python37-32\\python.exe"
  PYTHON3_64: "C:\\python37-64\\python.exe"
  PYINSTALLER: "C:\\python37-32\\scripts\\pyinstaller.exe"
  NSIS: "C:\\nsis\\makensis.exe"

.configure_environment: &configure_environment
  tags:
    - windows10
  before_script:
    - '$env:PYTHON3_32 -V'
    - '$env:PYTHON3_32 -m pip install --upgrade pip'
    - '$env:PYTHON3_32 -m pip install --upgrade -r requirements.txt'
    - '$env:PYTHON3_32 -m pip uninstall enum34 -y'

# Create documentation in all available languages so we'll have it at http://socializer.su/documentation
# this job is triggered on every commit to master, so we always will display the latest available version of the documentation in the website.
documentation:
  type: deploy
  script:
    - copy changelog.md doc\changelog.md
    - cd doc
    - '$env:PYTHON3_32 documentation_importer.py'
    - cd ..\src
    - '$env:PYTHON3_32 ..\doc\generator.py'
    - 'move documentation ..\'
    - cd ..\scripts
    - call genpot_interface.bat
    - call genpot_doc.bat
    - cd ..
    - move scripts\socializer.pot socializer.pot
    - move scripts\socializer-documentation.pot socializer-documentation.pot
  only:
    - master
  artifacts:
    paths:
    - documentation
    name: socializer_documentation
    expire_in: 30 days

alpha32:
  <<: *configure_environment
  type: deploy
  script:
    - copy changelog.md doc\changelog.md
    - cd doc
    - '$env:PYTHON3_32 documentation_importer.py'
    - cd ..\src
    - '$env:PYTHON3_32 ..\doc\generator.py'
    - '$env:PYTHON3_32 write_version_data.py'
    - '$env:PYTHON3_32 setup.py build'
    - '$env:NSIS installer_alpha.nsi'
    - cd ..
    - move src\socializer* .
    - cd scripts
    - '$env:PYTHON3_32 prepare_zipversion.py'
    - cd ..
    - move src\socializer.zip socializer_x86_alpha.zip
    - '$env:PYTHON3_32 scripts/generate_update_file.py'
    - '$env:PYTHON3_32 scripts/upload.py'
    - move socializer_x86_alpha.zip socializer_x86.zip
  only:
    - schedules
    - master
  artifacts:
    paths:
    - socializer_x86.zip
    name: socializer_alpha
    expire_in: 1 day

# Generates a new stable version of the application every tag.
stable:
  <<: *configure_environment
  type: deploy
  script:
    - copy changelog.md doc\changelog.md
    - cd doc
    - '$env:PYTHON3_32 documentation_importer.py'
    - cd ..\src
    - '$env:PYTHON3_32 ..\doc\generator.py'
    - '$env:PYTHON3_32 write_version_data.py'
    - '$env:PYTHON3_32 setup.py build'
    - '$env:NSIS installer.nsi'
    - cd ..
    - move src\socializer* .
    - cd scripts
    - '$env:PYTHON3_32 prepare_zipversion_cxfreeze.py'
    - cd ..
    - move src\socializer.zip socializer.zip
    - '$env:PYTHON3_32 scripts/upload.py'
  only:
    - tags