# Jobs to build the two channels in Socializer.
variables:
  PYTHON3: "C:\\python37\\python.exe"
  PYINSTALLER: "C:\\python37\\scripts\\pyinstaller.exe"
  PYTHON2: "C:\\python27\\python.exe"

alpha:
  type: deploy
  tags:
    - windows
  script:
    - pip install --upgrade pip
    - pip install --upgrade -r requirements.txt
    - copy changelog.md doc\changelog.md
    - cd doc
    - python documentation_importer.py
    - cd ..\src
    - python ..\doc\generator.py
    - python write_version_data.py
    - python setup.py py2exe
    - cd ..
    - cd scripts
    - python prepare_zipversion.py
    - cd ..
    - move src\socializer.zip socializer.zip
  only:
    - master
  artifacts:
    paths:
    - socializer.zip
    name: socializer
    expire_in: 1 week

alpha_python3:
  type: deploy
  tags:
    - windows10
  before_script:
    - '%PYTHON3% -v'
    - '%PYTHON3% -m pip install --upgrade pip'
    - '%PYTHON3% -m pip install --upgrade -r requirements.txt'
    - '%PYTHON3% -m pip install --upgrade pyenchant pypubsub'
    - '%PYTHON3% -m pip uninstall enum34 -y'
  script:
    - copy changelog.md doc\changelog.md
    - cd doc
    - '%PYTHON2% documentation_importer.py'
    - cd ..\src
    - '%PYTHON2% ..\doc\generator.py'
    - '%PYTHON3% write_version_data.py'
    - '%PYINSTALLER% main.spec'
    - cd ..
    - cd scripts
    - '%PYTHON3% prepare_zipversion.py'
    - cd ..
    - move src\socializer.zip socializer.zip
  only:
    - master
  artifacts:
    paths:
    - socializer.zip
    name: socializer_py3
    expire_in: 1 hour

stable:
  type: deploy
  tags:
    - windows
  script:
    - pip install --upgrade pip
    - pip install --upgrade -r requirements.txt
    - copy changelog.md doc\changelog.md
    - cd doc
    - python documentation_importer.py
    - cd ..\src
    - python ..\doc\generator.py
    - python setup.py py2exe
    - cd ..
    - cd scripts
    - python prepare_zipversion.py
    - cd ..
    - move src\socializer.zip socializer.zip
  only:
    - tags
  artifacts:
    paths:
    - socializer.zip
    name: socializer