production:
  type: deploy
  script:
    - pip install --upgrade -r requirements.txt
    - cd src
    - python setup.py py2exe
    - cd ..
    - move src\dist dist
  artifacts:
    paths:
    - dist/*
    expire_in: 1 week