production:
  type: deploy
  tags:
    - windows
  script:
    - pip install --upgrade pip
    - pip install --upgrade -r requirements.txt
    - cd doc
    - python documentation_importer.py
    - cd ..\src
    - python ..\doc\generator.py
    - python setup.py py2exe
    - cd ..
    - cd scripts
    - python prepare_zipversion.py
    - cd ..
    - move src\socializer.zip socializer.zip
  only:
    - tags
  artifacts:
    paths:
    - socializer.zip
    name: socializer
    expire_in: 1 week